services:
  postgres:
    image: postgres:16
    container_name: pipeline-postgres
    environment:
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
      POSTGRES_DB: pipeline_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./00-create-prefect-db.sh:/docker-entrypoint-initdb.d/00-create-prefect-db.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline_user -d pipeline_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    restart: unless-stopped
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://pipeline_user:pipeline_pass@postgres:5432/prefect_db"
      PREFECT_SERVER_API_HOST: "0.0.0.0"
    ports:
      - "4200:4200"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
